
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - batch.demo.io
  resources:
  - serviceexports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.demo.io
  resources:
  - serviceexports/finalizers
  verbs:
  - update
- apiGroups:
  - batch.demo.io
  resources:
  - serviceexports/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch.demo.io
  resources:
  - serviceimports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.demo.io
  resources:
  - serviceimports/finalizers
  verbs:
  - update
- apiGroups:
  - batch.demo.io
  resources:
  - serviceimports/status
  verbs:
  - get
  - patch
  - update
