# permissions for end users to view serviceexports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: serviceexport-viewer-role
rules:
- apiGroups:
  - batch.demo.io
  resources:
  - serviceexports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.demo.io
  resources:
  - serviceexports/status
  verbs:
  - get
